#!/bin/bash
DATASET1="../data/Arrhythmia_data_set"
DATASETA="Arrhythmia"
DATASET2="../data/gene_expression_cancer_RNA-Seq_data_set"
DATASETB="gene"
ACCFILE="SVM-DBSCAN"

echo "======================== dataset: arrhythmia ====================="
echo "original, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/train_data.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/test_data.csv -test_label_path $DATASET1/test_label.csv -normalize false -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 0.1 -SVM_kernel linear -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 300 -verbose false #> $ACCFILE-$DATASETA-original-linear.acc
echo "original, nor, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/train_data.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/test_data.csv -test_label_path $DATASET1/test_label.csv -normalize true -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 0.1 -SVM_kernel linear -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 100 -verbose false #> $ACCFILE-$DATASETA-original-nor-linear.acc
echo "original, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/train_data.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/test_data.csv -test_label_path $DATASET1/test_label.csv -normalize false -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel poly -SVM_kernel_gamma 1 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 300 -verbose false
echo "original, nor, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/train_data.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/test_data.csv -test_label_path $DATASET1/test_label.csv -normalize true -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel poly -SVM_kernel_gamma 50 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 300 -verbose false
echo "original, rbf"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/train_data.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/test_data.csv -test_label_path $DATASET1/test_label.csv -normalize false -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 0.1 -SVM_kernel poly -SVM_kernel_gamma 0.1 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 500 -verbose false
echo "original, nor, rbf"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/train_data.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/test_data.csv -test_label_path $DATASET1/test_label.csv -normalize true -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 0.1 -SVM_kernel poly -SVM_kernel_gamma 15 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 100 -verbose false
echo "original, sigmoid"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/train_data.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/test_data.csv -test_label_path $DATASET1/test_label.csv -normalize false -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 0.8 -SVM_kernel sigmoid -SVM_kernel_gamma 0.000001 -SVM_kernel_degree 1 -SVM_kernel_r 0.01 -DBSCAN_minPts 5 -DBSCAN_eps 500 -verbose false #> $ACCFILE-$DATASETA-original-sigmoid.acc
echo "original, nor, sigmoid"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/train_data.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/test_data.csv -test_label_path $DATASET1/test_label.csv -normalize true -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 0.8 -SVM_kernel sigmoid -SVM_kernel_gamma 0.000001 -SVM_kernel_degree 1 -SVM_kernel_r 0.05 -DBSCAN_minPts 2 -DBSCAN_eps 500 -verbose false #> $ACCFILE-$DATASETA-original-sigmoid.acc

echo "AE 32, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/AE_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/AE_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize false -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel linear -SVM_kernel_gamma 1 -SVM_kernel_degree 2 -SVM_kernel_r 4 -DBSCAN_minPts 2 -DBSCAN_eps 10 -verbose false #> $ACCFILE-$DATASETA-AE_32-linear.acc
echo "AE 32, nor, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/AE_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/AE_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize true -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel linear -SVM_kernel_gamma 1 -SVM_kernel_degree 2 -SVM_kernel_r 4 -DBSCAN_minPts 2 -DBSCAN_eps 5 -verbose false #> $ACCFILE-$DATASETA-AE_32-linear.acc
echo "AE 32, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/AE_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/AE_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize false -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 10 -SVM_kernel poly -SVM_kernel_gamma 1 -SVM_kernel_degree 2 -SVM_kernel_r 0 -DBSCAN_minPts 10 -DBSCAN_eps 500 -verbose false #> $ACCFILE-$DATASETA-AE_32-nor-ploy.acc
echo "AE 32, nor, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/AE_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/AE_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize true -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 10 -SVM_kernel poly -SVM_kernel_gamma 1 -SVM_kernel_degree 2 -SVM_kernel_r 0 -DBSCAN_minPts 10 -DBSCAN_eps 500 -verbose false #> $ACCFILE-$DATASETA-AE_32-nor-ploy.acc
echo "AE 32, rbf"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/AE_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/AE_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize false -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel rbf -SVM_kernel_gamma 0.3 -SVM_kernel_degree 2 -SVM_kernel_r 0.9 -DBSCAN_minPts 2 -DBSCAN_eps 100 -verbose false #> $ACCFILE-$DATASETA-AE_32-rbf.acc
echo "AE 32, nor, rbf"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/AE_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/AE_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize true -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel rbf -SVM_kernel_gamma 1 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 2 -DBSCAN_eps 100 -verbose false #> $ACCFILE-$DATASETA-AE_32-nor-rbf.acc
echo "AE 32, sigmoid"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/AE_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/AE_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize false -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 2 -SVM_kernel sigmoid -SVM_kernel_gamma 0.000001 -SVM_kernel_degree 2 -SVM_kernel_r 0.18 -DBSCAN_minPts 10 -DBSCAN_eps 500 -verbose false #> $ACCFILE-$DATASETA-AE_32-sigmoid.acc
echo "AE 32, nor, sigmoid"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/AE_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/AE_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize true -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 2 -SVM_kernel sigmoid -SVM_kernel_gamma 0.00001 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 500 -verbose false #> $ACCFILE-$DATASETA-AE_32-nor-sigmoid.acc

echo "PCA 32, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/PCA_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/PCA_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize false -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel linear -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 500 -verbose false
echo "PCA 32, nor, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/PCA_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/PCA_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize true -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel linear -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 500 -verbose false
echo "PCA 32, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/PCA_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/PCA_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize false -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel poly -SVM_kernel_gamma 1000 -SVM_kernel_degree 2 -SVM_kernel_r 5 -DBSCAN_minPts 10 -DBSCAN_eps 50 -verbose false
echo "PCA 32, nor, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/PCA_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/PCA_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize true -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel poly -SVM_kernel_gamma 51 -SVM_kernel_degree 2 -SVM_kernel_r 5 -DBSCAN_minPts 10 -DBSCAN_eps 50 -verbose false
echo "PCA 32, rbf"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/PCA_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/PCA_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize false -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 0.5 -SVM_kernel rbf -SVM_kernel_gamma 500 -SVM_kernel_degree 2 -SVM_kernel_r 5 -DBSCAN_minPts 10 -DBSCAN_eps 500 -verbose false
echo "PCA 32, nor, rbf"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/PCA_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/PCA_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize true -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 0.5 -SVM_kernel rbf -SVM_kernel_gamma 0.05 -SVM_kernel_degree 2 -SVM_kernel_r 10 -DBSCAN_minPts 2 -DBSCAN_eps 13 -verbose false
echo "PCA 32, sigmoid"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/PCA_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/PCA_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize false -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 0.8 -SVM_kernel sigmoid -SVM_kernel_gamma 0.00001 -SVM_kernel_degree 2 -SVM_kernel_r 0.7 -DBSCAN_minPts 10 -DBSCAN_eps 500 -verbose false
echo "PCA 32, nor, sigmoid"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET1/PCA_train_data_32.csv -train_label_path $DATASET1/train_label.csv -test_data_path $DATASET1/PCA_test_data_32.csv -test_label_path $DATASET1/test_label.csv -normalize true -KNOWN_CNT 8 -UNKNOWN_CNT 5 -SVM_converge_lim 1e-7 -SVM_punishment 0.8 -SVM_kernel sigmoid -SVM_kernel_gamma 0.05 -SVM_kernel_degree 2 -SVM_kernel_r 0.04 -DBSCAN_minPts 10 -DBSCAN_eps 50 -verbose false

echo "================== dataset: gene expression cancer ====================="
echo "original, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/train_data.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/test_data.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 0.1 -SVM_kernel linear -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 20 -DBSCAN_eps 8000 -verbose false
echo "original, nor, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/train_data.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/test_data.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 0.1 -SVM_kernel linear -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 22 -DBSCAN_eps 800 -verbose false
echo "original, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/train_data.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/test_data.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 0.5 -SVM_kernel poly -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 22 -DBSCAN_eps 700
echo "original, nor, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/train_data.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/test_data.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel poly -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 22 -DBSCAN_eps 80
echo "original, rbf (it may not converge)"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/train_data.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/test_data.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-1 -SVM_punishment 1 -SVM_kernel rbf -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 22 -DBSCAN_eps 8000 -verbose false
echo "original, nor, rbf (it may not converge)"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/train_data.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/test_data.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-1 -SVM_punishment 0.01 -SVM_kernel rbf -SVM_kernel_gamma 0.5 -SVM_kernel_degree 2 -SVM_kernel_r 0 -DBSCAN_minPts 22 -DBSCAN_eps 80 -verbose false
echo "original, sigmoid (it may not converge)"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/train_data.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/test_data.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-1 -SVM_punishment 0.01 -SVM_kernel sigmoid -SVM_kernel_gamma 0.000001 -SVM_kernel_degree 2 -SVM_kernel_r 0.01 -DBSCAN_minPts 22 -DBSCAN_eps 80 -verbose false
echo "original, nor, sigmoid (it may not converge)"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/train_data.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/test_data.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-1 -SVM_punishment 0.1 -SVM_kernel sigmoid -SVM_kernel_gamma 0.0001 -SVM_kernel_degree 2 -SVM_kernel_r 0.1 -DBSCAN_minPts 22 -DBSCAN_eps 80 -verbose false

echo "AE 30, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/AE_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/AE_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel linear -SVM_kernel_gamma 1 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 2 -DBSCAN_eps 25 -verbose false
echo "AE 30, nor, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/AE_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/AE_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel linear -SVM_kernel_gamma 1 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 23 -verbose false
echo "AE 30, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/AE_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/AE_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel poly -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 2 -DBSCAN_eps 10 -verbose false
echo "AE 30, nor, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/AE_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/AE_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel poly -SVM_kernel_gamma 1 -SVM_kernel_degree 2 -SVM_kernel_r 0.1 -DBSCAN_minPts 10 -DBSCAN_eps 500 -verbose false
echo "AE 30, rbf"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/AE_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/AE_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 0.5 -SVM_kernel rbf -SVM_kernel_gamma 1.6 -SVM_kernel_degree 2 -SVM_kernel_r 0.1 -DBSCAN_minPts 10 -DBSCAN_eps 50 -verbose false
echo "AE 30, nor, rbf"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/AE_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/AE_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel rbf -SVM_kernel_gamma 4 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 22 -DBSCAN_eps 50 -verbose false
echo "AE 30, sigmoid"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/AE_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/AE_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 5 -SVM_kernel sigmoid -SVM_kernel_gamma 0.0000001 -SVM_kernel_degree 2 -SVM_kernel_r 5 -DBSCAN_minPts 10 -DBSCAN_eps 50 -verbose false
echo "AE 30, nor, sigmoid"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/AE_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/AE_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel sigmoid -SVM_kernel_gamma 1 -SVM_kernel_degree 1 -SVM_kernel_r 0 -DBSCAN_minPts 22 -DBSCAN_eps 50 -verbose false

echo "PCA 30, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel linear -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 460 -kmeans_converge_lim 1e-7 -verbose false
echo "PCA 30, nor, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel linear -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 460 -kmeans_converge_lim 1e-7 -verbose false
echo "PCA 30, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel poly -SVM_kernel_gamma 0.6 -SVM_kernel_degree 2 -SVM_kernel_r 3 -DBSCAN_minPts 5 -DBSCAN_eps 200 -verbose false
echo "PCA 30, nor, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel poly -SVM_kernel_gamma 0.005 -SVM_kernel_degree -10 -SVM_kernel_r 0 -DBSCAN_minPts 10 -DBSCAN_eps 20 -verbose false
echo "PCA 30, rbf"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel rbf -SVM_kernel_gamma 0.0005 -SVM_kernel_degree 2 -SVM_kernel_r 100 -DBSCAN_minPts 10 -DBSCAN_eps 460 -kmeans_converge_lim 1e-7 -verbose false
echo "PCA 30, nor, rbf"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel rbf -SVM_kernel_gamma 0.0001 -SVM_kernel_degree 2 -SVM_kernel_r 10 -DBSCAN_minPts 10 -DBSCAN_eps 460 -kmeans_converge_lim 1e-7 -verbose false
echo "PCA 30, sigmoid"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel sigmoid -SVM_kernel_gamma 0.0000165 -SVM_kernel_degree 2 -SVM_kernel_r 0.001 -DBSCAN_minPts 10 -DBSCAN_eps 460 -kmeans_converge_lim 1e-7 -verbose false
echo "PCA 30, sigmoid, nor"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_30.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_30.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel sigmoid -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 0.001 -DBSCAN_minPts 10 -DBSCAN_eps 460 -kmeans_converge_lim 1e-7 -verbose false

echo "PCA 100, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_100.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_100.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel linear -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 460 -kmeans_converge_lim 1e-7 -verbose false
echo "PCA 100, nor, linear"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_100.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_100.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel linear -SVM_kernel_gamma 2 -SVM_kernel_degree 2 -SVM_kernel_r 1 -DBSCAN_minPts 10 -DBSCAN_eps 460 -kmeans_converge_lim 1e-7 -verbose false
echo "PCA 100, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_100.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_100.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel poly -SVM_kernel_gamma 1.5656 -SVM_kernel_degree 2 -SVM_kernel_r 3.69483 -DBSCAN_minPts 4 -DBSCAN_eps 141.497 -verbose false
echo "PCA 100, nor, poly"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_100.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_100.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel poly -SVM_kernel_gamma 5 -SVM_kernel_degree -10 -SVM_kernel_r 0 -DBSCAN_minPts 10 -DBSCAN_eps 20 -verbose false

echo "PCA 100, rbf"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_100.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_100.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel rbf -SVM_kernel_gamma 0.0005 -SVM_kernel_degree 2 -SVM_kernel_r 100 -DBSCAN_minPts 10 -DBSCAN_eps 460 -kmeans_converge_lim 1e-7 -verbose false
echo "PCA 100, nor, rbf"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_100.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_100.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel rbf -SVM_kernel_gamma 0.0001 -SVM_kernel_degree 2 -SVM_kernel_r 10 -DBSCAN_minPts 10 -DBSCAN_eps 460 -kmeans_converge_lim 1e-7 -verbose false

echo "PCA 100, sigmoid"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_100.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_100.csv -test_label_path $DATASET2/test_label.csv -normalize false -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel sigmoid -SVM_kernel_gamma 0.0000165 -SVM_kernel_degree 2 -SVM_kernel_r 0.001 -DBSCAN_minPts 10 -DBSCAN_eps 460 -kmeans_converge_lim 1e-7 -verbose false
echo "PCA 100, sigmoid, nor"
./main.elf -repeats 1 -classifying SVM -clustering DBSCAN -train_data_path $DATASET2/PCA_train_data_100.csv -train_label_path $DATASET2/train_label.csv -test_data_path $DATASET2/PCA_test_data_100.csv -test_label_path $DATASET2/test_label.csv -normalize true -KNOWN_CNT 3 -UNKNOWN_CNT 2 -SVM_converge_lim 1e-7 -SVM_punishment 1 -SVM_kernel sigmoid -SVM_kernel_gamma 0.53961 -SVM_kernel_degree 2 -SVM_kernel_r 0.0155175 -DBSCAN_minPts 6 -DBSCAN_eps 124.178 -kmeans_converge_lim 1e-7 -verbose false
